### ISSUE TITLE
Screenshot not visible

### ISSUE THREAD

**Issue by dhellwich** [evilpenguin/RemoveRecents#1]
Whenever I quit an app, the app to the right loses its screenshot.

iPhone 5S iOS 7.0.4

![bdhr_82ceaajjsq](https://f.cloud.github.com/assets/5427776/1959050/0c5c2702-8225-11e3-8857-8a7e911a3ebf.png)

**Comment by evilpenguin** [comment]
does this still happen?

**Comment by dhellwich** [comment]
Don't know, I don't use the tweak anymore

**Comment by evilpenguin** [comment]
OK... I just released a new version for ios8...
