### ISSUE TITLE
please make it ios8-compatible

### ISSUE THREAD

**Issue by 191919** [evilpenguin/RemoveRecents#2]
1.3.5 is not compatible with iOS 8.

**Comment by vgmoose** [comment]
+1, iOS 8 compatibility would be incredibly useful. [The summary](http://i.imgur.com/CFtW1Zz.jpg) is spot on about the stock task switcher being annoying.

**Comment by evilpenguin** [comment]
I added ios8 support

**Comment by vgmoose** [comment]
thank you so much!
